version: '3.8'

services:

  zookeeper1:
    image: "${ZOOKEEPER_IMAGE}"
    hostname: zookeeper1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:1888:1889;2181 server.2=zookeeper2:1888:1889;2181 server.3=zookeeper3:1888:1889;2181
    volumes:
      - 'zookeeper1_data:/data'
      - 'zookeeper1_log:/datalog'
    networks:
      - lan
    deploy:
      placement:
        constraints:
          - "node.labels.${CLUSTER} == 1"

  zookeeper2:
    image: "${ZOOKEEPER_IMAGE}"
    hostname: zookeeper2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:1888:1889;2181 server.2=zookeeper2:1888:1889;2181 server.3=zookeeper3:1888:1889;2181
    volumes:
      - 'zookeeper2_data:/data'
      - 'zookeeper2_log:/datalog'
    networks:
      - lan
    deploy:
      placement:
        constraints:
          - "node.labels.${CLUSTER} == 2"

  zookeeper3:
    image: "${ZOOKEEPER_IMAGE}"
    hostname: zookeeper3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:1888:1889;2181 server.2=zookeeper2:1888:1889;2181 server.3=zookeeper3:1888:1889;2181
    volumes:
      - 'zookeeper3_data:/data'
      - 'zookeeper3_log:/datalog'
    networks:
      - lan
    deploy:
      placement:
        constraints:
          - "node.labels.${CLUSTER} == 3"

  kafka1:
    image: "${KAFKA_IMAGE}"
    env_file:
      - './kafka.env'
      - './secrets/keystores.pass'
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ADVERTISED_LISTENERS: "SECURE://${BROKER1}:9093"
    secrets:
      - source: 'keystore'
        target: '/run/secrets/kafka.jks'
      - source: 'truststore'
        target: '/run/secrets/trust.jks'
    volumes:
      - 'kafka1_data:/data'
    networks:
      - lan
    deploy:
      placement:
        constraints:
          - "node.labels.${CLUSTER} == 1"

  kafka2:
    image: "${KAFKA_IMAGE}"
    env_file:
      - './kafka.env'
      - './secrets/keystores.pass'
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ADVERTISED_LISTENERS: "SECURE://${BROKER2}:9093"
    secrets:
      - source: 'keystore'
        target: '/run/secrets/kafka.jks'
      - source: 'truststore'
        target: '/run/secrets/trust.jks'
    volumes:
      - 'kafka2_data:/data'
    networks:
      - lan
    deploy:
      placement:
        constraints:
          - "node.labels.${CLUSTER} == 2"

  kafka3:
    image: "${KAFKA_IMAGE}"
    env_file:
      - './kafka.env'
      - './secrets/keystores.pass'
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ADVERTISED_LISTENERS: "SECURE://${BROKER3}:9093"
    secrets:
      - source: 'keystore'
        target: '/run/secrets/kafka.jks'
      - source: 'truststore'
        target: '/run/secrets/trust.jks'
    volumes:
      - 'kafka3_data:/data'
    networks:
      - lan
    deploy:
      placement:
        constraints:
          - "node.labels.${CLUSTER} == 3"

volumes:
  zookeeper1_data:
  zookeeper1_log:
  zookeeper2_data:
  zookeeper2_log:
  zookeeper3_data:
  zookeeper3_log:
  kafka1_data:
  kafka2_data:
  kafka3_data:

secrets:
  keystore:
    file: './secrets/kafka.jks'
  truststore:
    file: './secrets/trust.jks'

networks:
  lan: {}
