version: '3.8'

services:

  zookeeper1:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  zookeeper2:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  zookeeper3:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  kafka1:
    environment:
      KAFKA_LISTENERS: SECURE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: SECURE://node1.mac.wales:9093
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  kafka2:
    environment:
      KAFKA_LISTENERS: SECURE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: SECURE://node1.mac.wales:9094
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  kafka3:
    environment:
      KAFKA_LISTENERS: SECURE://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: SECURE://node1.mac.wales:9095
    ports:
      - target: 9095
        published: 9095
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1
