version: '3.8'

services:

  zookeeper1:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  zookeeper2:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==2

  zookeeper3:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==3

  kafka1:
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  kafka2:
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.cmb==2

  kafka3:
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.cmb==3
