version: '3.8'

services:

  zookeeper1:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  zookeeper2:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  zookeeper3:
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  kafka1:
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  kafka2:
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1

  kafka3:
    ports:
      - target: 9095
        published: 9095
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.labels.cmb==1
