---
- name: deploy certificates
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  become: true

  tasks:

  - name: delete kafka directory
    file:
      path: '/opt/kafka'
      state: absent
