---
- name: generate all certificates
  hosts: kafka1
  gather_facts: false
  any_errors_fatal: true
  become: true
  tasks:

  - name: create kafka{n}.env environment file
    copy:
      dest: '/root/stack-kafka/{{ item }}.env'
      content: "KAFKA_LISTENERS={{ hostvars[item]['KAFKA_LISTENERS'] }}\nKAFKA_ADVERTISED_LISTENERS={{ hostvars[item]['KAFKA_ADVERTISED_LISTENERS'] }}\n"
    with_items: "{{ groups['all'] }}"

  - name: make kafka directory
    file:
      path: '/opt/kafka'
      state: directory

  - name: link deployment utilities
    file:
      src: /root/stack-kafka/bin
      dest: /opt/kafka/deploy
      state: link

  - name: generate all certificates
    shell: "/opt/kafka/deploy/cert-make-all.sh {{ kafka_base_dn | quote }} kafka1 kafka2 kafka3 {{ kafka_brokers | join(' ') }}"

- name: deploy certificates
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  become: true
  tasks:

  - name: make security directory
    file:
      path: '/opt/kafka/security'
      state: directory

  - name: copy trust certificates and keys
    copy:
      src: "{{ item }}"
      dest: '/opt/kafka/security'
    with_items:
      - '/opt/kafka/ca/trust.jks'
      - '/opt/kafka/ca/trust.pass'

  - name: copy host certificates and keys
    copy:
      src: '/tmp/security/'
      dest: '/opt/kafka/security'
